name: hello_world
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Dio for http connection
  dio: ^3.0.10
  # Data connection checker
  data_connection_checker: ^0.3.4
  # Bloc for state management
  flutter_bloc: ^6.0.5
  # Value Equality
  equatable: ^1.2.5
  # Dependency injection
  get_it: ^5.0.1
  # Shared Preferences
  shared_preferences: ^0.5.12+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Mock Tests
  mockito: ^4.1.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
